name: Generate Snake

on:
  schedule:
    # 每 12 小时跑一次
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#1A5F7A&color_dots=#ebedf0,#c6dcf1,#8ab6e8,#3E88C7,#14304F
            dist/github-snake-dark.svg?color_snake=#5B8DEF&color_dots=#161b22,#14304F,#1A5F7A,#3E88C7,#5B8DEF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
